name: Git Diff Check
description: "Check repository for whitespace errors using git diff --check against empty tree"
author: Frieder Bluemle
branding:
  icon: check
  color: blue
runs:
  using: "composite"
  steps:
    - name: Check for whitespace errors
      shell: bash
      run: |
        set -euo pipefail
        git -c core.whitespace=fix,-indent-with-non-tab,trailing-space,cr-at-eol diff --check 4b825dc642cb6eb9a060e54bf8d69288fbee4904
