name: test
on:
  push:
    branches: [ '*' ]
  pull_request:
jobs:
  pass-case:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create clean file
        run: echo "clean" > clean.txt
      - uses: ./
  fail-case:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Create trailing whitespace
        run: printf "bad    \n" > bad.txt
      - id: run
        uses: ./
      - name: Assert it failed
        if: steps.run.outcome == 'success'
        run: echo "Expected failure but step succeeded" >&2 && exit 1
